// De stad zonder regels: Kowloon Walled City, and the cyberpunk stories that kept its maze alive.
// Question order is fixed once published: saved answers are stored by index.
import * as art from './art.js';
import { animate } from './motion.js';

export default {
  slug: 'kowloon',
  name: 'Kowloon',
  number: '08',
  meta: {
    title: 'De Stad Zonder Regels: Kowloon Walled City en Cyberpunk',
    description: 'Een echte stad zonder zon op de grond, en het doolhof dat in films en games bleef leven. Een interactief Nederlands leesavontuur voor Alex.',
  },
  card: {
    title: 'De stad zonder *regels*',
    blurb: 'Neon, steegjes en een doolhof dat nooit helemaal verdween. Stap Kowloon Walled City binnen.',
  },
  home: {
    label: 'LEESREIS 08 · HONGKONG',
    greeting: 'Hé Alex, kijk eens omhoog.',
    heading: ['De stad zonder', '*regels.*'],
    description: 'Een piepklein stukje land midden in Hongkong, vol steegjes, neon en verhalen. Ontdek Kowloon Walled City, en waarom die stad in games en films blijft leven.',
    cta: 'Stap de steeg in',
    location: 'KOWLOON, HONGKONG',
    stamp: ['KIJK', 'Kowloon', 'STAD & SPEL'],
    caption: 'Waar de huizen bijna alle lucht wegnamen.',
    routeHeading: 'Jouw route door de stad',
  },
  chapters: [
    {
      title: 'Geen film, maar echt',
      short: 'De stad',
      label: 'KOWLOON · MIDDEN IN HONGKONG',
      icon: '✳',
      aside: 'Een streepje lucht',
      caption: 'Hoge muren, neon en kabels. Tussen de daken blijft maar een klein stukje hemel over.',
      note: 'DE REIS BEGINT',
    },
    {
      title: 'Huizen bovenop huizen',
      short: 'Bovenop elkaar',
      label: 'HET FORT · STEEDS MEER KAMERS',
      icon: '♜',
      aside: 'Een fort onder de stad',
      caption: 'Onderaan het oude fort. Daarboven steeds nieuwe kamers, naast twee kleine velden.',
      note: 'KIJK EENS GOED',
    },
    {
      title: 'Een doolhof van neon',
      short: 'Binnenin',
      label: 'DE STEEGJES · KABELS EN NEON',
      icon: '❧',
      aside: 'Donker, maar niet alleen',
      caption: 'Kabels, druppels en een kom die wordt gedeeld. Tik hieronder en gluur in het noedelfabriekje.',
      note: 'BLIJF NIEUWSGIERIG',
      variants: [{ id: 'steeg', label: 'De steeg' }, { id: 'noedels', label: 'Noedels' }],
    },
    {
      title: 'De ultieme Cyberpunk-stad',
      short: 'Cyberpunk',
      label: 'CYBERPUNK · HIGH TECH, LOW LIFE',
      icon: '✺',
      aside: 'De stad in een scherm',
      caption: 'Achter je de megastad. In je handen dezelfde stad, nu als film en als game.',
      note: 'KIJK TWEE KEER',
    },
    {
      title: 'Een park en een scherm',
      short: 'Nog altijd',
      label: '1993 · VAN STAD NAAR PARK',
      icon: '☼',
      aside: 'De zon mag er weer bij',
      caption: 'Eerst het rustige park. Tik hieronder en je ziet de stad die er eerder stond.',
      note: 'HET VERHAAL GAAT DOOR',
      variants: [{ id: 'park', label: 'Het park' }, { id: 'stad', label: 'De stad' }],
    },
  ],
  dictionary: {
    verantwoordelijk: 'Dat je de taak hebt om voor iets of iemand te zorgen.',
    dichtstbevolkte: 'De plek waar de meeste mensen op een klein stukje grond wonen.',
    wirwarren: 'Een grote warboel van draden of buizen die door elkaar hangen.',
    onbevoegde: 'Zonder toestemming of diploma om dat werk te doen.',
    Triades: 'De naam van de maffia in dit verhaal: bendes die veel macht hadden.',
    geavanceerde: 'Heel modern en knap gemaakt.',
    megasteden: 'Enorm grote steden met heel veel mensen.',
    virtuele: 'Niet in het echt, maar in een computer, film of game.',
  },
  questions: [
    {
      q: 'Wat was Kowloon Walled City volgens de tekst?',
      options: [
        'Een filmdecor dat alleen in een game bestond.',
        'Een groot eiland ver van Hongkong.',
        'Een echt, piepklein stukje land midden in Hongkong.',
        'Een stadspark dat er altijd al was.',
      ],
      answer: 2,
      chapter: 0,
      explanation: 'De tekst zegt dat dit geen film was, maar werkelijkheid. Kowloon Walled City was een piepklein stukje land midden in Hongkong.',
    },
    {
      q: 'Wat was deze plek oorspronkelijk?',
      options: [
        'Een Chinees militair fort.',
        'Een Brits politiebureau.',
        'Een grote noedelfabriek.',
        'Een sciencefictionfilm.',
      ],
      answer: 0,
      chapter: 1,
      explanation: 'De tekst zegt het meteen: oorspronkelijk was het een Chinees militair fort.',
    },
    {
      q: 'Wat was het gevolg van 50.000 mensen op een oppervlakte zo groot als een paar voetbalvelden?',
      options: [
        'De neonlampen gingen meteen uit.',
        'China en Groot-Brittannië gingen er samen wonen.',
        'De stad werd nog diezelfde dag een park.',
        'Het werd de dichtstbevolkte plek op aarde.',
      ],
      answer: 3,
      chapter: 1,
      explanation: 'Dit is oorzaak en gevolg. Omdat er zoveel mensen op zo’n klein stukje grond woonden, was het de dichtstbevolkte plek op aarde.',
    },
    {
      q: 'Wat betekent ‘onbevoegde tandartsen’ hier?',
      options: [
        'Tandartsen die alleen in het donker werkten.',
        'Tandartsen zonder toestemming voor dat werk.',
        'Tandartsen uit een groot ziekenhuis.',
        'Tandartsen die noedels maakten.',
      ],
      answer: 1,
      chapter: 2,
      explanation: 'Onbevoegd betekent hier: zonder toestemming of diploma. In de stad werkten tandartsen die dat officieel niet mochten.',
    },
    {
      q: 'Wie had er volgens de tekst veel macht in de stad?',
      options: [
        'De politie van Hongkong.',
        'De bewoners van het latere stadspark.',
        'De maffia, de Triades.',
        'De makers van het spel Cyberpunk 2077.',
      ],
      answer: 2,
      chapter: 2,
      explanation: 'De tekst zegt dat de maffia (de Triades) er veel macht had. Tegelijk was het ook een hechte gemeenschap, waar mensen elkaar hielpen.',
    },
    {
      q: 'Wat bedoelt de tekst met ‘high tech, low life’?',
      options: [
        'Geavanceerde technologie, maar gewone mensen in donkere, overvolle steden.',
        'Een toekomst waarin niemand nog technologie gebruikt.',
        'Alleen rijke mensen in hoge, brandschone torens.',
        'Een leeg park met één oude spelcomputer in het gras.',
      ],
      answer: 0,
      chapter: 3,
      explanation: 'De tekst legt het zelf uit: een toekomst met geavanceerde technologie, maar waar gewone mensen in donkere, rommelige en overvolle megasteden leven, vol neon.',
    },
    {
      q: 'Wat is de belangrijkste boodschap van de hele tekst?',
      options: [
        'Kowloon Walled City staat nog steeds midden in Hongkong.',
        'Cyberpunk gaat alleen over snelle auto’s.',
        'In de stad golden juist extra veel regels.',
        'De chaotische stad is afgebroken, maar in cyberpunk-werelden leeft het doolhof voort.',
      ],
      answer: 3,
      chapter: 4,
      explanation: 'In 1993 werd de Walled City afgebroken en veranderd in een rustig park. In de virtuele cyberpunk-werelden leeft het bizarre doolhof nog altijd voort.',
    },
  ],
  written: [
    {
      q: 'Waarom golden er in Kowloon Walled City eigenlijk geen wetten en regels?',
      label: 'TEKSTBEGRIP & ANALYSE',
      chapter: 1,
      model: 'Toen de Britten de rest van Hongkong gingen besturen, werd dit stukje land vergeten. Zowel China als Groot-Brittannië voelden zich niet verantwoordelijk. Daardoor werd het een plek zonder wetten en regels.',
    },
    {
      q: 'Waarom was het op de onderste verdiepingen en in de steegjes altijd donker?',
      label: 'TEKSTBEGRIP & ANALYSE',
      chapter: 0,
      model: 'De gebouwen stonden zo dicht op elkaar dat het zonlicht de grond nooit raakte. Daarom was het in de steegjes en op de onderste verdiepingen altijd donker. Die plekken werden verlicht door flikkerende neonlampen.',
    },
  ],
  quiz: { mcEyebrow: 'JOUW STADKENNIS', mcHeading: 'Tijd voor de steegquiz, Alex.' },
  completion: {
    heading: ['Mooi gedaan,', '*stadsontdekker Alex.*'],
    text: 'Van een fort onder de huizen tot neon, noedels en een rustig park: jij hebt dit doolhof echt leren lezen. De stad is weg, maar het verhaal is van jou.',
    tag: 'VOOR ALEX · VAN PAPA JEREMY ♡',
  },
  art,
  animate,
};
